### ISSUE TITLE
Add params in launch file, to be able to control some robot specs

### ISSUE THREAD

**Issue by elpimous** [moribots/minitaur_from_scratch#12]
The use of params in ROS launchfile could help change some values in poses or walk specs :

- robot height
- Step Length
- Step velocity

- what policy model use.

**Comment by moribots** [comment]
Thanks Vincent! There is already a ros param for selecting your policy. Step length is controlled by pushing the right joystick forward, and step velocity is controlled by the bottom left and right bumpers (See README)

I will add ones for your other requested features now.

**Comment by elpimous** [comment]
very reactive, Thanks Maurice !

**Comment by moribots** [comment]
I've just made the changes. You can modify everything that contributes to Spot's motion in the `mini_ros/config/` directory ([link](https://github.com/moribots/spot_mini_mini/tree/spot/mini_ros/config))

Give it a shot and let me know what you think!

Commit: `708c4769547660adf2646db44bdde33915288b63`

**Comment by elpimous** [comment]
Hey, Maurice !! Nearly perfect !
Perhaps could you  add : 
- x gravity position
- body height
