### ISSUE TITLE
Non strainge forward walk

### ISSUE THREAD

**Issue by tarasborov** [moribots/minitaur_from_scratch#13]
Hello!
At first, I would like to say that your project is great and well-done.
I went through the project and tried to simulate the spot:
1) Run ./env_tester.py. 
2) Define StepLenght=0.05
However, the spot were walking forward with small shifting in left side. I saw that you tried fix that by AutoYaw (if I understood corectly). 
Could you tell me why this problem appears? Is this problem in a BezierGait algorithm?
I am looking forwad for your answer. Thanks.

**Comment by moribots** [comment]
Hi, thanks!

This happens because of the system dynamics.

**Comment by tarasborov** [comment]
Thanks for your answer! 
Do you mean that inertial of each link causes a change in foot trajectories? 
If I want to walk straight forward, should I design a yaw controller?

**Comment by moribots** [comment]
Essentially, yes. The combination of foot impacts and inertia causes this behavior. A yaw controller is the simplest solution to deal with this problem.

If you think in terms of a high level controller (xy velocities, yaw velocity), it's a straightforward thing to have in your pipeline.

**Comment by tarasborov** [comment]
Thank You!
