### ISSUE TITLE
Starting walking motion

### ISSUE THREAD

**Issue by sayantanauddy** [moribots/minitaur_from_scratch#16]
First of all, thank you for providing this very nice repository! I have a question about the simulation:

After cloning the repo and installing the dependencies, I am able to start the simulation using `./env_tester.py`. Using the provided sliders, I am able to change the roll, pitch, yaw etc. and the robot shows the changes in the simulation. However, I am not able to start the walking motion. Is there some specific step that I need to perform to start the walk?

**Comment by moribots** [comment]
You can change `Step Length` to walk forward or backward. While this value is non-zero, you can change `Lateral Fraction` to strafe left and right, and `Yaw Rate` to twist.
